### PR TITLE
Initial Dashrows Component commit

### PR DESCRIPTION
**Pull request by mihai-mihalache**

### CODE REVIEW

**Review by jgolieb — COMMENTED** [review]
Why did you base dashrows on `<ul>`, rather than `<table>` or Bootstrap's grid? I don't think `<ul>` is semantically appropriate, but the bigger issue is you're creating another system for laying out columns and rows when there are already options available for that.

**Comment by mihai-mihalache** [comment]
> Why did you base dashrows on `<ul>`, rather than `<table>` or Bootstrap's grid? I don't think `<ul>` is semantically appropriate, but the bigger issue is you're creating another system for laying out columns and rows when there are already options available for that.

The **table** approach was way too rigid so not all the design details could be implemented (row spacing, header aspect, etc). The **bootstrap grid** would also not be flexible enough to accommodate all the requirements of the design. The new grid is required in order to isolate this component (cleaner code) rather than overwriting css props for rows and cols. It also gets rid of some confusion that could arise from making dashrows the same as grid rows

**Comment by jgolieb** [comment]
OK, can you just use `<div>` instead of `<ul>`?

**Comment by mihai-mihalache** [comment]
Updated!

**Review by jgolieb — APPROVED** [review]
I'll approve this because I know it is WIP, but here are some more comments:
- Remove `list-style`, etc. that is no longer needed for `<div>`
- For font sizes, use variables as much as possible and also use the `px()` function
- For colors, use the map functions, i.e. `theme-color()`, etc. instead of the variables directly
- Put variables in the `_variables.scss` file
- Don't use `!important` unless you absolutely must, and in those cases, leave a comment explaining why ;)
- From now on, we should make sure to run `gulp lint-sass` and resolve all issues before submitting a PR

**Pull request merged**
